apiVersion: v1
kind: Service
metadata:
  name: go-container-nodeport
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: go-container-app
